// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/app/proto/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletedStatus int32

const (
	DeletedStatus_NONE           DeletedStatus = 0 // not deleted
	DeletedStatus_MARKED_DELETED DeletedStatus = 1 // record marked as deleted
)

// Enum value maps for DeletedStatus.
var (
	DeletedStatus_name = map[int32]string{
		0: "NONE",
		1: "MARKED_DELETED",
	}
	DeletedStatus_value = map[string]int32{
		"NONE":           0,
		"MARKED_DELETED": 1,
	}
)

func (x DeletedStatus) Enum() *DeletedStatus {
	p := new(DeletedStatus)
	*p = x
	return p
}

func (x DeletedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeletedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_app_proto_shortener_proto_enumTypes[0].Descriptor()
}

func (DeletedStatus) Type() protoreflect.EnumType {
	return &file_internal_app_proto_shortener_proto_enumTypes[0]
}

func (x DeletedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeletedStatus.Descriptor instead.
func (DeletedStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{0}
}

// Request for creating a short link with plain URL (string).
type CreateShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // original full URL to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortRequest) Reset() {
	*x = CreateShortRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortRequest) ProtoMessage() {}

func (x *CreateShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortRequest.ProtoReflect.Descriptor instead.
func (*CreateShortRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Response containing created short URL.
type CreateShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // shortened URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortResponse) Reset() {
	*x = CreateShortResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortResponse) ProtoMessage() {}

func (x *CreateShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortResponse.ProtoReflect.Descriptor instead.
func (*CreateShortResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Message for redirect request by hash
type FindByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByHashRequest) Reset() {
	*x = FindByHashRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByHashRequest) ProtoMessage() {}

func (x *FindByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByHashRequest.ProtoReflect.Descriptor instead.
func (*FindByHashRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *FindByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// Response for FindByHash
type FindByHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullUrl       string                 `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`              // original URL to redirect to
	Status        DeletedStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=shortener.DeletedStatus" json:"status,omitempty"` // status of the record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByHashResponse) Reset() {
	*x = FindByHashResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByHashResponse) ProtoMessage() {}

func (x *FindByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByHashResponse.ProtoReflect.Descriptor instead.
func (*FindByHashResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *FindByHashResponse) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *FindByHashResponse) GetStatus() DeletedStatus {
	if x != nil {
		return x.Status
	}
	return DeletedStatus_NONE
}

// Request for fetching all URLs by user ID (userID is extracted from metadata/auth context)
type FindAllByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserIDRequest) Reset() {
	*x = FindAllByUserIDRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserIDRequest) ProtoMessage() {}

func (x *FindAllByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{4}
}

type FindAllByUserIDResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Urls          []*FindURLByUserIDResponse `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserIDResponse) Reset() {
	*x = FindAllByUserIDResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserIDResponse) ProtoMessage() {}

func (x *FindAllByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByUserIDResponse) GetUrls() []*FindURLByUserIDResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type FindURLByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindURLByUserIDResponse) Reset() {
	*x = FindURLByUserIDResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindURLByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindURLByUserIDResponse) ProtoMessage() {}

func (x *FindURLByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindURLByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindURLByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *FindURLByUserIDResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *FindURLByUserIDResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateShortRequestBatchItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortRequestBatchItemRequest) Reset() {
	*x = CreateShortRequestBatchItemRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortRequestBatchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortRequestBatchItemRequest) ProtoMessage() {}

func (x *CreateShortRequestBatchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortRequestBatchItemRequest.ProtoReflect.Descriptor instead.
func (*CreateShortRequestBatchItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShortRequestBatchItemRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateShortRequestBatchItemRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateShortRequestBatchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortRequestBatchItemResponse) Reset() {
	*x = CreateShortRequestBatchItemResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortRequestBatchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortRequestBatchItemResponse) ProtoMessage() {}

func (x *CreateShortRequestBatchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortRequestBatchItemResponse.ProtoReflect.Descriptor instead.
func (*CreateShortRequestBatchItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *CreateShortRequestBatchItemResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateShortRequestBatchItemResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchCreateRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Batch         []*CreateShortRequestBatchItemRequest `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRequest) Reset() {
	*x = BatchCreateRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRequest) ProtoMessage() {}

func (x *BatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCreateRequest) GetBatch() []*CreateShortRequestBatchItemRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

type BatchCreateResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Batch         []*CreateShortRequestBatchItemResponse `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateResponse) Reset() {
	*x = BatchCreateResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateResponse) ProtoMessage() {}

func (x *BatchCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *BatchCreateResponse) GetBatch() []*CreateShortRequestBatchItemResponse {
	if x != nil {
		return x.Batch
	}
	return nil
}

// Request message for async deletion of multiple short links.
type DeleteLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // IDs of links to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinksRequest) Reset() {
	*x = DeleteLinksRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinksRequest) ProtoMessage() {}

func (x *DeleteLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinksRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinksRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteLinksRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Empty response message for acknowledgment.
type DeleteLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinksResponse) Reset() {
	*x = DeleteLinksResponse{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinksResponse) ProtoMessage() {}

func (x *DeleteLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinksResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinksResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{12}
}

// Statistic response message.
type Statistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statistic) Reset() {
	*x = Statistic{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic) ProtoMessage() {}

func (x *Statistic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic.ProtoReflect.Descriptor instead.
func (*Statistic) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *Statistic) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *Statistic) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

// Empty request message.
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_internal_app_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_shortener_proto_rawDescGZIP(), []int{14}
}

var File_internal_app_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_app_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\"internal/app/proto/shortener.proto\x12\tshortener\"&\n" +
	"\x12CreateShortRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"-\n" +
	"\x13CreateShortResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"'\n" +
	"\x11FindByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"a\n" +
	"\x12FindByHashResponse\x12\x19\n" +
	"\bfull_url\x18\x01 \x01(\tR\afullUrl\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.shortener.DeletedStatusR\x06status\"\x18\n" +
	"\x16FindAllByUserIDRequest\"Q\n" +
	"\x17FindAllByUserIDResponse\x126\n" +
	"\x04urls\x18\x01 \x03(\v2\".shortener.FindURLByUserIDResponseR\x04urls\"Y\n" +
	"\x17FindURLByUserIDResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"n\n" +
	"\"CreateShortRequestBatchItemRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"i\n" +
	"#CreateShortRequestBatchItemResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"Y\n" +
	"\x12BatchCreateRequest\x12C\n" +
	"\x05batch\x18\x01 \x03(\v2-.shortener.CreateShortRequestBatchItemRequestR\x05batch\"[\n" +
	"\x13BatchCreateResponse\x12D\n" +
	"\x05batch\x18\x01 \x03(\v2..shortener.CreateShortRequestBatchItemResponseR\x05batch\"&\n" +
	"\x12DeleteLinksRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x15\n" +
	"\x13DeleteLinksResponse\"5\n" +
	"\tStatistic\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users\"\x0e\n" +
	"\fEmptyRequest*-\n" +
	"\rDeletedStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\x12\n" +
	"\x0eMARKED_DELETED\x10\x012\xe1\x03\n" +
	"\x10ShortenerService\x12L\n" +
	"\vCreateShort\x12\x1d.shortener.CreateShortRequest\x1a\x1e.shortener.CreateShortResponse\x12I\n" +
	"\n" +
	"FindByHash\x12\x1c.shortener.FindByHashRequest\x1a\x1d.shortener.FindByHashResponse\x12X\n" +
	"\x0fFindAllByUserID\x12!.shortener.FindAllByUserIDRequest\x1a\".shortener.FindAllByUserIDResponse\x12L\n" +
	"\vCreateBatch\x12\x1d.shortener.BatchCreateRequest\x1a\x1e.shortener.BatchCreateResponse\x12L\n" +
	"\vDeleteLinks\x12\x1d.shortener.DeleteLinksRequest\x1a\x1e.shortener.DeleteLinksResponse\x12>\n" +
	"\rGetStatistics\x12\x17.shortener.EmptyRequest\x1a\x14.shortener.StatisticB Z\x1einternal/app/proto/shortenerpbb\x06proto3"

var (
	file_internal_app_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_app_proto_shortener_proto_rawDescData []byte
)

func file_internal_app_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_app_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_app_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_proto_shortener_proto_rawDesc), len(file_internal_app_proto_shortener_proto_rawDesc)))
	})
	return file_internal_app_proto_shortener_proto_rawDescData
}

var file_internal_app_proto_shortener_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_app_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_app_proto_shortener_proto_goTypes = []any{
	(DeletedStatus)(0),                          // 0: shortener.DeletedStatus
	(*CreateShortRequest)(nil),                  // 1: shortener.CreateShortRequest
	(*CreateShortResponse)(nil),                 // 2: shortener.CreateShortResponse
	(*FindByHashRequest)(nil),                   // 3: shortener.FindByHashRequest
	(*FindByHashResponse)(nil),                  // 4: shortener.FindByHashResponse
	(*FindAllByUserIDRequest)(nil),              // 5: shortener.FindAllByUserIDRequest
	(*FindAllByUserIDResponse)(nil),             // 6: shortener.FindAllByUserIDResponse
	(*FindURLByUserIDResponse)(nil),             // 7: shortener.FindURLByUserIDResponse
	(*CreateShortRequestBatchItemRequest)(nil),  // 8: shortener.CreateShortRequestBatchItemRequest
	(*CreateShortRequestBatchItemResponse)(nil), // 9: shortener.CreateShortRequestBatchItemResponse
	(*BatchCreateRequest)(nil),                  // 10: shortener.BatchCreateRequest
	(*BatchCreateResponse)(nil),                 // 11: shortener.BatchCreateResponse
	(*DeleteLinksRequest)(nil),                  // 12: shortener.DeleteLinksRequest
	(*DeleteLinksResponse)(nil),                 // 13: shortener.DeleteLinksResponse
	(*Statistic)(nil),                           // 14: shortener.Statistic
	(*EmptyRequest)(nil),                        // 15: shortener.EmptyRequest
}
var file_internal_app_proto_shortener_proto_depIdxs = []int32{
	0,  // 0: shortener.FindByHashResponse.status:type_name -> shortener.DeletedStatus
	7,  // 1: shortener.FindAllByUserIDResponse.urls:type_name -> shortener.FindURLByUserIDResponse
	8,  // 2: shortener.BatchCreateRequest.batch:type_name -> shortener.CreateShortRequestBatchItemRequest
	9,  // 3: shortener.BatchCreateResponse.batch:type_name -> shortener.CreateShortRequestBatchItemResponse
	1,  // 4: shortener.ShortenerService.CreateShort:input_type -> shortener.CreateShortRequest
	3,  // 5: shortener.ShortenerService.FindByHash:input_type -> shortener.FindByHashRequest
	5,  // 6: shortener.ShortenerService.FindAllByUserID:input_type -> shortener.FindAllByUserIDRequest
	10, // 7: shortener.ShortenerService.CreateBatch:input_type -> shortener.BatchCreateRequest
	12, // 8: shortener.ShortenerService.DeleteLinks:input_type -> shortener.DeleteLinksRequest
	15, // 9: shortener.ShortenerService.GetStatistics:input_type -> shortener.EmptyRequest
	2,  // 10: shortener.ShortenerService.CreateShort:output_type -> shortener.CreateShortResponse
	4,  // 11: shortener.ShortenerService.FindByHash:output_type -> shortener.FindByHashResponse
	6,  // 12: shortener.ShortenerService.FindAllByUserID:output_type -> shortener.FindAllByUserIDResponse
	11, // 13: shortener.ShortenerService.CreateBatch:output_type -> shortener.BatchCreateResponse
	13, // 14: shortener.ShortenerService.DeleteLinks:output_type -> shortener.DeleteLinksResponse
	14, // 15: shortener.ShortenerService.GetStatistics:output_type -> shortener.Statistic
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_app_proto_shortener_proto_init() }
func file_internal_app_proto_shortener_proto_init() {
	if File_internal_app_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_proto_shortener_proto_rawDesc), len(file_internal_app_proto_shortener_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_app_proto_shortener_proto_depIdxs,
		EnumInfos:         file_internal_app_proto_shortener_proto_enumTypes,
		MessageInfos:      file_internal_app_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_app_proto_shortener_proto = out.File
	file_internal_app_proto_shortener_proto_goTypes = nil
	file_internal_app_proto_shortener_proto_depIdxs = nil
}
